/**
 * Universal Subtitle Live (UniSub Live)
 * Supported 20 Languages Configuration & UI Localization
 */

export const LANGUAGES = [
  { code: 'ko', name: '한국어', native: '한국어', flag: '🇰🇷', stt: 'ko-KR', prompt: 'Korean', style: 'Use polite, formal Korean (존댓말).' },
  { code: 'th', name: '태국어', native: 'ภาษาไทย', flag: '🇹🇭', stt: 'th-TH', prompt: 'Thai', style: 'Use polite particles like ครับ/ค่ะ where natural.' },
  { code: 'en', name: '영어', native: 'English', flag: '🇺🇸', stt: 'en-US', prompt: 'English', style: 'Use clear, natural, polite conversational English.' },
  { code: 'vi', name: '베트남어', native: 'Tiếng Việt', flag: '🇻🇳', stt: 'vi-VN', prompt: 'Vietnamese', style: 'Use natural, polite Vietnamese conversational phrasing.' },
  { code: 'zh', name: '중국어', native: '中文', flag: '🇨🇳', stt: 'zh-CN', prompt: 'Chinese (Simplified)', style: 'Use clear, natural simplified Chinese.' },
  { code: 'ja', name: '일본어', native: '日本語', flag: '🇯🇵', stt: 'ja-JP', prompt: 'Japanese', style: 'Use polite Japanese (です/ます form).' },
  { code: 'uz', name: '우즈베키스탄어', native: 'Oʻzbekcha', flag: '🇺🇿', stt: 'uz-UZ', prompt: 'Uzbek', style: 'Use polite, natural Uzbek conversational phrasing.' },
  { code: 'ru', name: '러시아어', native: 'Русский', flag: '🇷🇺', stt: 'ru-RU', prompt: 'Russian', style: 'Use clear, polite Russian conversational phrasing.' },
  { code: 'mn', name: '몽골어', native: 'Монгол хэл', flag: '🇲🇳', stt: 'mn-MN', prompt: 'Mongolian', style: 'Use polite, natural Mongolian conversational phrasing.' },
  { code: 'kk', name: '카자흐스탄어', native: 'Қазақша', flag: '🇰🇿', stt: 'kk-KZ', prompt: 'Kazakh', style: 'Use polite, natural Kazakh conversational phrasing.' },
  { code: 'ky', name: '키르기스스탄어', native: 'Кыргызча', flag: '🇰🇬', stt: 'ky-KG', prompt: 'Kyrgyz', style: 'Use polite, natural Kyrgyz conversational phrasing.' },
  { code: 'id', name: '인도네시아어', native: 'Bahasa Indonesia', flag: '🇮🇩', stt: 'id-ID', prompt: 'Indonesian', style: 'Use polite, natural Indonesian conversational phrasing.' },
  { code: 'ms', name: '말레이시아어', native: 'Bahasa Melayu', flag: '🇲🇾', stt: 'ms-MY', prompt: 'Malay', style: 'Use polite, natural Malay conversational phrasing.' },
  { code: 'km', name: '캄보디아어', native: 'ភាសាខ្មែរ', flag: '🇰🇭', stt: 'km-KH', prompt: 'Khmer', style: 'Use polite, natural Khmer conversational phrasing.' },
  { code: 'my', name: '미얀마어', native: 'မြန်မာဘာသာ', flag: '🇲🇲', stt: 'my-MM', prompt: 'Burmese', style: 'Use polite, natural Burmese conversational phrasing.' },
  { code: 'ne', name: '네팔어', native: 'नेपाली', flag: '🇳🇵', stt: 'ne-NP', prompt: 'Nepali', style: 'Use polite, natural Nepali conversational phrasing.' },
  { code: 'lo', name: '라오스어', native: 'ພາສາລາວ', flag: '🇱🇦', stt: 'lo-LA', prompt: 'Lao', style: 'Use polite, natural Lao conversational phrasing.' },
  { code: 'si', name: '스리랑카어', native: 'සිංහල', flag: '🇱🇰', stt: 'si-LK', prompt: 'Sinhala', style: 'Use polite, natural Sinhala conversational phrasing.' },
  { code: 'bn', name: '방글라데시어', native: 'বাংলা', flag: '🇧🇩', stt: 'bn-BD', prompt: 'Bengali', style: 'Use polite, natural Bengali conversational phrasing.' },
  { code: 'ur', name: '파키스탄어', native: 'اردو', flag: '🇵🇰', stt: 'ur-PK', prompt: 'Urdu', style: 'Use polite, natural Urdu conversational phrasing.' }
];

export const LANGUAGE_MAP = Object.fromEntries(
  LANGUAGES.map(lang => [lang.code, lang])
);

export function getLanguage(code) {
  return LANGUAGE_MAP[code] || LANGUAGE_MAP.en || {
    code: code || 'en',
    name: code || 'English',
    native: code || 'English',
    flag: '🌐',
    stt: 'en-US',
    prompt: code || 'English',
    style: ''
  };
}

export const UI_TEXTS = {
  ko: {
    tagline: '실시간 양방향 대화 자막 통번역',
    subdesc: '20개국 글로벌 실시간 자막 통번역 시스템',
    selectLang: '내 언어 선택 / Select Your Language',
    searchPlaceholder: '언어 또는 국가 검색 (예: 베트남, English, 中文)...',
    createTitle: '새 통번역 회의 방 만들기',
    createDesc: '버튼을 누르면 회의 코드 및 QR 접속 코드가 생성됩니다.',
    createBtn: '새 회의 생성 (Create Room)',
    roomCodeLabel: '회의 코드:',
    qrDesc: '아래 QR코드를 파트너 휴대폰으로 스캔하거나 링크를 전달하세요.',
    copyLinkBtn: '초대 링크 복사하기',
    copiedNotice: '초대 링크가 복사되었습니다!',
    enterRoomBtn: '회의 입장하기 (Enter Room)',
    joinTitle: '초대받은 회의 코드로 입장',
    joinInputPlaceholder: '예: TC-8492',
    joinBtn: '참여',
    settingsBtn: '통번역 엔진 및 Gemini AI 설정',
    waitingSubtitle: '상대방의 자막을 기다리는 중입니다...',
    speaking: '음성 감지 중... (Speaking)',
    preview: '내가 보낸 자막 미리보기',
    inputPlaceholder: '자막 메시지를 입력하거나 마이크로 말씀하세요...',
    send: '전송',
    leave: '나가기',
    connected: '연결 완료 (Connected)',
    waitingPartner: '상대방 접속 대기 중...',
    transcript: '대화록 (Transcript)',
    saveTxt: '저장 (.txt)',
    noHistory: '아직 기록된 대화 자막이 없습니다.'
  },
  th: {
    tagline: 'ระบบแปลคำบรรยายการสนทนาแบบเรียลไทม์',
    subdesc: 'ระบบแปลคำบรรยายสด 2 ทิศทาง 20 ภาษาผ่านเบราว์เซอร์',
    selectLang: 'เลือกภาษาของคุณ (Select Your Language)',
    searchPlaceholder: 'ค้นหาภาษาหรือประเทศ...',
    createTitle: 'สร้างห้องประชุมแปลภาษาใหม่',
    createDesc: 'กดปุ่มเพื่อสร้างรหัสห้องประชุมและคิวอาร์โค้ด',
    createBtn: 'สร้างห้องประชุม (Create Room)',
    roomCodeLabel: 'รหัสห้องประชุม:',
    qrDesc: 'สแกนคิวอาร์โค้ดด้านล่างหรือส่งลิงก์ให้คู่สนทนาของคุณ',
    copyLinkBtn: 'คัดลอกลิงก์คำเชิญ',
    copiedNotice: 'คัดลอกลิงก์คำเชิญเรียบร้อยแล้ว!',
    enterRoomBtn: 'เข้าสู่ห้องประชุม (Enter Room)',
    joinTitle: 'เข้าร่วมด้วยรหัสห้องประชุม',
    joinInputPlaceholder: 'ตัวอย่าง: TC-8492',
    joinBtn: 'เข้าร่วม',
    settingsBtn: 'การตั้งค่าเอ็นจินแปลภาษา & Gemini AI',
    waitingSubtitle: 'กำลังรอคำบรรยายจากคู่สนทนา...',
    speaking: 'กำลังตรวจจับเสียง... (Speaking)',
    preview: 'ตัวอย่างคำบรรยายของฉัน',
    inputPlaceholder: 'พิมพ์ข้อความหรือกดไมโครโฟนเพื่อพูด...',
    send: 'ส่ง',
    leave: 'ออก',
    connected: 'เชื่อมต่อแล้ว (Connected)',
    waitingPartner: 'กำลังรอคู่สนทนาเข้าร่วม...',
    transcript: 'บันทึกการสนทนา (Transcript)',
    saveTxt: 'บันทึก (.txt)',
    noHistory: 'ยังไม่มีประวัติการสนทนา'
  },
  en: {
    tagline: 'Real-time 2-Way Subtitle Translator',
    subdesc: '20-Language Global Real-Time Subtitle Translation System',
    selectLang: 'Select Your Language',
    searchPlaceholder: 'Search language or country (e.g., Vietnam, Korean, Español)...',
    createTitle: 'Create New Meeting Room',
    createDesc: 'Click the button to generate a room code and QR code.',
    createBtn: 'Create Room',
    roomCodeLabel: 'Room Code:',
    qrDesc: 'Scan the QR code below or share the link with your partner.',
    copyLinkBtn: 'Copy Invite Link',
    copiedNotice: 'Invite link copied to clipboard!',
    enterRoomBtn: 'Enter Room',
    joinTitle: 'Join with Room Code',
    joinInputPlaceholder: 'e.g. TC-8492',
    joinBtn: 'Join',
    settingsBtn: 'Translation Engine & Gemini AI Settings',
    waitingSubtitle: 'Waiting for partner subtitles...',
    speaking: 'Listening... (Speaking)',
    preview: 'My Subtitle Preview',
    inputPlaceholder: 'Type a message or tap microphone to speak...',
    send: 'Send',
    leave: 'Leave',
    connected: 'Connected',
    waitingPartner: 'Waiting for partner to join...',
    transcript: 'Transcript History',
    saveTxt: 'Save (.txt)',
    noHistory: 'No conversation history yet.'
  },
  vi: {
    tagline: 'Dịch phụ đề trò chuyện 2 chiều thời gian thực',
    subdesc: 'Hệ thống phụ đề đa ngôn ngữ 20 quốc gia trên trình duyệt di động',
    selectLang: 'Chọn ngôn ngữ của bạn (Select Your Language)',
    searchPlaceholder: 'Tìm kiếm ngôn ngữ hoặc quốc gia...',
    createTitle: 'Tạo phòng họp dịch thuật mới',
    createDesc: 'Nhấn nút để tạo mã phòng và mã QR tham gia.',
    createBtn: 'Tạo phòng (Create Room)',
    roomCodeLabel: 'Mã phòng:',
    qrDesc: 'Quét mã QR bên dưới hoặc gửi liên kết cho đối tác của bạn.',
    copyLinkBtn: 'Sao chép liên kết mời',
    copiedNotice: 'Đã sao chép liên kết!',
    enterRoomBtn: 'Vào phòng (Enter Room)',
    joinTitle: 'Tham gia bằng mã phòng',
    joinInputPlaceholder: 'Ví dụ: TC-8492',
    joinBtn: 'Tham gia',
    settingsBtn: 'Cài đặt công cụ dịch & Gemini AI',
    waitingSubtitle: 'Đang đợi phụ đề từ đối tác...',
    speaking: 'Đang nhận diện giọng nói...',
    preview: 'Xem trước phụ đề của tôi',
    inputPlaceholder: 'Nhập tin nhắn hoặc bật micro để nói...',
    send: 'Gửi',
    leave: 'Rời phòng',
    connected: 'Đã kết nối (Connected)',
    waitingPartner: 'Đang chờ đối tác tham gia...',
    transcript: 'Lịch sử cuộc gọi',
    saveTxt: 'Lưu (.txt)',
    noHistory: 'Chưa có bản ghi cuộc hội thoại nào.'
  },
  zh: {
    tagline: '实时双向语音字幕同声翻译',
    subdesc: '支持20国语言的全球实时字幕翻译系统',
    selectLang: '选择您的语言 / Select Your Language',
    searchPlaceholder: '搜索语言或国家...',
    createTitle: '创建新的翻译会议室',
    createDesc: '点击按钮生成房间代码和二维码。',
    createBtn: '创建房间 (Create Room)',
    roomCodeLabel: '房间代码:',
    qrDesc: '扫描下方二维码或将链接发送给对方。',
    copyLinkBtn: '复制邀请链接',
    copiedNotice: '邀请链接已复制！',
    enterRoomBtn: '进入房间 (Enter Room)',
    joinTitle: '使用房间代码加入',
    joinInputPlaceholder: '例如: TC-8492',
    joinBtn: '加入',
    settingsBtn: '翻译引擎与 Gemini AI 设置',
    waitingSubtitle: '正在等待对方的字幕...',
    speaking: '正在收音中... (Speaking)',
    preview: '我的字幕预览',
    inputPlaceholder: '输入字幕消息或点击麦克风说话...',
    send: '发送',
    leave: '退出',
    connected: '已连接 (Connected)',
    waitingPartner: '等待对方加入...',
    transcript: '对话记录 (Transcript)',
    saveTxt: '保存 (.txt)',
    noHistory: '暂无对话记录。'
  },
  ja: {
    tagline: 'リアルタイム双方向字幕翻訳システム',
    subdesc: '20カ国対応 モバイル対応リアルタイム字幕翻訳',
    selectLang: '言語を選択してください / Select Language',
    searchPlaceholder: '言語または国を検索...',
    createTitle: '新しい翻訳ルームを作成',
    createDesc: 'ボタンを押すとルームコードとQRコードが生成されます。',
    createBtn: 'ルーム作成 (Create Room)',
    roomCodeLabel: 'ルームコード:',
    qrDesc: 'QRコードをスキャンするか、招待リンクを相手に送信してください。',
    copyLinkBtn: '招待リンクをコピー',
    copiedNotice: 'リンクをコピーしました！',
    enterRoomBtn: 'ルームに入る (Enter Room)',
    joinTitle: 'ルームコードで参加',
    joinInputPlaceholder: '例: TC-8492',
    joinBtn: '参加',
    settingsBtn: '翻訳エンジン & Gemini AI 設定',
    waitingSubtitle: '相手の字幕を待っています...',
    speaking: '音声認識中... (Speaking)',
    preview: '送信字幕プレビュー',
    inputPlaceholder: 'メッセージを入力またはマイクで発言...',
    send: '送信',
    leave: '退出',
    connected: '接続完了 (Connected)',
    waitingPartner: '相手の接続を待機中...',
    transcript: '対話履歴 (Transcript)',
    saveTxt: '保存 (.txt)',
    noHistory: '会話履歴はまだありません。'
  },
  uz: {
    tagline: 'Haqiqiy vaqtda ikki tomonlama subtitr tarjimoni',
    subdesc: '20 tilda mobil brauzer orqali jonli subtitr tarjimasi',
    selectLang: 'Tilingizni tanlang / Select Your Language',
    searchPlaceholder: 'Til yoki davlatni qidirish...',
    createTitle: 'Yangi xona yaratish',
    createDesc: 'Xona kodi va QR kodni yaratish uchun tugmani bosing.',
    createBtn: 'Xona yaratish (Create Room)',
    roomCodeLabel: 'Xona kodi:',
    qrDesc: 'Quyidagi QR kodni skanerlang yoki havolani sherigingizga yuboring.',
    copyLinkBtn: 'Havolani nusxalash',
    copiedNotice: 'Taklif havolasi nusxalandi!',
    enterRoomBtn: 'Xonaga kirish (Enter Room)',
    joinTitle: 'Xona kodi orqali kirish',
    joinInputPlaceholder: 'Masalan: TC-8492',
    joinBtn: 'Kirish',
    settingsBtn: 'Tarjima tizimi & Gemini AI sozlamalari',
    waitingSubtitle: 'Suhbatdosh subtitrlarini kutmoqda...',
    speaking: 'Ovoz tinglanmoqda...',
    preview: 'Yuborilgan subtitr koʻrinishi',
    inputPlaceholder: 'Xabar yozing yoki mikrofonga gapiring...',
    send: 'Yuborish',
    leave: 'Chiqish',
    connected: 'Ulandi (Connected)',
    waitingPartner: 'Suhbatdosh ulanishi kutilmoqda...',
    transcript: 'Suhbat tarixi',
    saveTxt: 'Saqlash (.txt)',
    noHistory: 'Hali suhbatlar mavjud emas.'
  },
  ru: {
    tagline: 'Двусторонний перевод субтитров в реальном времени',
    subdesc: 'Система синхронного перевода субтитров на 20 языках',
    selectLang: 'Выберите ваш язык / Select Your Language',
    searchPlaceholder: 'Поиск языка или страны...',
    createTitle: 'Создать новую комнату перевода',
    createDesc: 'Нажмите кнопку для создания кода комнаты и QR-кода.',
    createBtn: 'Создать комнату (Create Room)',
    roomCodeLabel: 'Код комнаты:',
    qrDesc: 'Отсканируйте QR-код или отправьте ссылку собеседнику.',
    copyLinkBtn: 'Скопировать ссылку',
    copiedNotice: 'Ссылка скопирована в буфер обмена!',
    enterRoomBtn: 'Войти в комнату (Enter Room)',
    joinTitle: 'Войти по коду комнаты',
    joinInputPlaceholder: 'Например: TC-8492',
    joinBtn: 'Войти',
    settingsBtn: 'Настройки перевода и Gemini AI',
    waitingSubtitle: 'Ожидание субтитров собеседника...',
    speaking: 'Идет распознавание речи...',
    preview: 'Предпросмотр моих субтитров',
    inputPlaceholder: 'Введите текст или нажмите микрофон для речи...',
    send: 'Отправить',
    leave: 'Выйти',
    connected: 'Подключено (Connected)',
    waitingPartner: 'Ожидание подключения собеседника...',
    transcript: 'История разговора',
    saveTxt: 'Сохранить (.txt)',
    noHistory: 'История разговора пока пуста.'
  },
  mn: {
    tagline: 'Бодит цагийн 2 талт орчуулгын систем',
    subdesc: '20 орны хэл дээр шууд хадмал орчуулга хийх систем',
    selectLang: 'Хэлээ сонгоно уу (Select Your Language)',
    searchPlaceholder: 'Хэл эсвэл улс хайх...',
    createTitle: 'Шинэ уулзалтын өрөө үүсгэх',
    createDesc: 'Өрөөний код болон QR код үүсгэхийн тулд товчлуурыг дарна уу.',
    createBtn: 'Өрөө үүсгэх (Create Room)',
    roomCodeLabel: 'Өрөөний код:',
    qrDesc: 'Доорх QR кодыг уншуулах эсвэл холбоосыг хамтрагчдаа илгээнэ үү.',
    copyLinkBtn: 'Урилгын холбоосыг хуулах',
    copiedNotice: 'Холбоосыг хууллаа!',
    enterRoomBtn: 'Өрөө рүү орох (Enter Room)',
    joinTitle: 'Өрөөний кодоор орох',
    joinInputPlaceholder: 'Жишээ: TC-8492',
    joinBtn: 'Орох',
    settingsBtn: 'Орчуулгын систем болон Gemini AI тохиргоо',
    waitingSubtitle: 'Харилцагчийн хадмал орчуулгыг хүлээж байна...',
    speaking: 'Яриаг таньж байна...',
    preview: 'Миний хадмал орчуулга',
    inputPlaceholder: 'Зурвас бичих эсвэл микрофон дээр дарж ярина уу...',
    send: 'Илгээх',
    leave: 'Гарах',
    connected: 'Холбогдлоо (Connected)',
    waitingPartner: 'Харилцагчийг хүлээж байна...',
    transcript: 'Ярианы тэмдэглэл',
    saveTxt: 'Хадгалах (.txt)',
    noHistory: 'Ярианы түүх одоогоор алга байна.'
  },
  id: {
    tagline: 'Penerjemah Subtitel Percakapan 2 Arah Real-time',
    subdesc: 'Sistem terjemahan subtitel langsung 20 bahasa via ponsel',
    selectLang: 'Pilih Bahasa Anda (Select Your Language)',
    searchPlaceholder: 'Cari bahasa atau negara...',
    createTitle: 'Buat Ruang Pertemuan Baru',
    createDesc: 'Klik tombol untuk membuat kode ruang dan kode QR.',
    createBtn: 'Buat Ruang (Create Room)',
    roomCodeLabel: 'Kode Ruang:',
    qrDesc: 'Pindai kode QR di bawah atau bagikan tautan ke mitra Anda.',
    copyLinkBtn: 'Salin Tautan Undangan',
    copiedNotice: 'Tautan disalin ke papan klip!',
    enterRoomBtn: 'Masuk Ruang (Enter Room)',
    joinTitle: 'Gabung dengan Kode Ruang',
    joinInputPlaceholder: 'Contoh: TC-8492',
    joinBtn: 'Gabung',
    settingsBtn: 'Pengaturan Mesin Terjemahan & Gemini AI',
    waitingSubtitle: 'Menunggu subtitel lawan bicara...',
    speaking: 'Mendengarkan... (Speaking)',
    preview: 'Pratinjau Subtitel Saya',
    inputPlaceholder: 'Ketik pesan atau ketuk mikrofon untuk bicara...',
    send: 'Kirim',
    leave: 'Keluar',
    connected: 'Terhubung (Connected)',
    waitingPartner: 'Menunggu mitra bergabung...',
    transcript: 'Riwayat Transkrip',
    saveTxt: 'Simpan (.txt)',
    noHistory: 'Belum ada riwayat percakapan.'
  },
  ms: {
    tagline: 'Penterjemah Sarikata Perbualan 2 Hala Masa Nyata',
    subdesc: 'Sistem terjemahan sarikata langsung 20 bahasa melalui telefon',
    selectLang: 'Pilih Bahasa Anda (Select Your Language)',
    searchPlaceholder: 'Cari bahasa atau negara...',
    createTitle: 'Cipta Bilik Mesyuarat Baru',
    createDesc: 'Klik butang untuk menjana kod bilik dan kod QR.',
    createBtn: 'Cipta Bilik (Create Room)',
    roomCodeLabel: 'Kod Bilik:',
    qrDesc: 'Imbas kod QR di bawah atau kongsi pautan kepada rakan anda.',
    copyLinkBtn: 'Salin Pautan Jemputan',
    copiedNotice: 'Pautan disalin!',
    enterRoomBtn: 'Masuk Bilik (Enter Room)',
    joinTitle: 'Sertai dengan Kod Bilik',
    joinInputPlaceholder: 'Cth: TC-8492',
    joinBtn: 'Sertai',
    settingsBtn: 'Tetapan Enjin Terjemahan & Gemini AI',
    waitingSubtitle: 'Menunggu sarikata daripada pasangan anda...',
    speaking: 'Mendengar... (Speaking)',
    preview: 'Pratonton Sarikata Saya',
    inputPlaceholder: 'Taip mesej atau tekan mikrofon untuk bercakap...',
    send: 'Hantar',
    leave: 'Keluar',
    connected: 'Tersambung (Connected)',
    waitingPartner: 'Menunggu pasangan menyertai...',
    transcript: 'Sejarah Perbualan',
    saveTxt: 'Simpan (.txt)',
    noHistory: 'Tiada sejarah perbualan lagi.'
  },
  km: {
    tagline: 'ប្រព័ន្ធបកប្រែចំណងជើងរងការសន្ទនាផ្ទាល់',
    subdesc: 'ប្រព័ន្ធបកប្រែចំណងជើងរងផ្ទាល់ ២០ ភាសាតាមទូរស័ព្ទ',
    selectLang: 'ជ្រើសរើសភាសារបស់អ្នក (Select Language)',
    searchPlaceholder: 'ស្វែងរកភាសា...',
    createTitle: 'បង្កើតបន្ទប់ប្រជុំថ្មី',
    createDesc: 'ចុចប៊ូតុងដើម្បីបង្កើតកូដបន្ទប់ និង QR Code។',
    createBtn: 'បង្កើតបន្ទប់ (Create Room)',
    roomCodeLabel: 'កូដបន្ទប់:',
    qrDesc: 'ស្កេន QR Code ខាងក្រោម ឬផ្ញើតំណភ្ជាប់ទៅកាន់ដៃគូរបស់អ្នក។',
    copyLinkBtn: 'ចម្លងតំណអញ្ជើញ',
    copiedNotice: 'បានចម្លងតំណភ្ជាប់!',
    enterRoomBtn: 'ចូលបន្ទប់ (Enter Room)',
    joinTitle: 'ចូលដោយប្រើកូដបន្ទប់',
    joinInputPlaceholder: 'ឧទាហរណ៍: TC-8492',
    joinBtn: 'ចូលរួម',
    settingsBtn: 'ការកំណត់ប្រព័ន្ធបកប្រែ & Gemini AI',
    waitingSubtitle: 'កំពុងរង់ចាំចំណងជើងរងពីដៃគូ...',
    speaking: 'កំពុងស្តាប់...',
    preview: 'មើលចំណងជើងរងរបស់ខ្ញុំ',
    inputPlaceholder: 'វាយបញ្ចូលសារ ឬចុចមីក្រូហ្វូន...',
    send: 'ផ្ញើ',
    leave: 'ចាកចេញ',
    connected: 'បានភ្ជាប់ (Connected)',
    waitingPartner: 'កំពុងរង់ចាំដៃគូ...',
    transcript: 'កំណត់ត្រាការសន្ទនា',
    saveTxt: 'រក្សាទុក (.txt)',
    noHistory: 'មិនទាន់មានប្រវត្តិការសន្ទនានៅឡើយទេ។'
  },
  my: {
    tagline: 'တိုက်ရိုက် အပြန်အလှန် စာတန်းထိုး ဘာသာပြန်စနစ်',
    subdesc: 'ဘာသာစကား ၂၀ ဖြင့် တိုက်ရိုက် စာတန်းထိုး ဘာသာပြန်စနစ်',
    selectLang: 'သင့်ဘာသာစကားကို ရွေးချယ်ပါ',
    searchPlaceholder: 'ဘာသာစကား သို့မဟုတ် နိုင်ငံ ရှာဖွေပါ...',
    createTitle: 'အစည်းအဝေး အခန်းအသစ် ဖန်တီးပါ',
    createDesc: 'အခန်းကုဒ်နှင့် QR ကုဒ် ဖန်တီးရန် ခလုတ်ကို နှိပ်ပါ။',
    createBtn: 'အခန်း ဖန်တီးပါ (Create Room)',
    roomCodeLabel: 'အခန်းကုဒ်:',
    qrDesc: 'အောက်ပါ QR ကုဒ်ကို စကင်န်ဖတ်ပါ သို့မဟုတ် လင့်ခ်ကို မျှဝေပါ။',
    copyLinkBtn: 'ဖိတ်ခေါ်လင့်ခ်ကို ကူးယူပါ',
    copiedNotice: 'လင့်ခ်ကို ကူးယူပြီးပါပြီ!',
    enterRoomBtn: 'အခန်းထဲသို့ ဝင်ပါ',
    joinTitle: 'အခန်းကုဒ်ဖြင့် ဝင်ရောက်ပါ',
    joinInputPlaceholder: 'ဥပမာ: TC-8492',
    joinBtn: 'ပါဝင်မည်',
    settingsBtn: 'ဘာသာပြန်စနစ်နှင့် Gemini AI ဆက်တင်များ',
    waitingSubtitle: 'မိတ်ဖက်၏ စာတန်းထိုးကို စောင့်နေသည်...',
    speaking: 'အသံဖမ်းယူနေသည်...',
    preview: 'ကျွန်ုပ်၏ စာတန်းထိုး အကြိုကြည့်ရှုမှု',
    inputPlaceholder: 'စာရိုက်ပါ သို့မဟုတ် မိုက်ခရိုဖုန်းကို နှိပ်ပါ...',
    send: 'ပို့မည်',
    leave: 'ထွက်မည်',
    connected: 'ချိတ်ဆက်ပြီးပါပြီ (Connected)',
    waitingPartner: 'မိတ်ဖက်ချိတ်ဆက်မှုကို စောင့်နေသည်...',
    transcript: 'စကားပြောမှတ်တမ်း',
    saveTxt: 'သိမ်းဆည်းမည် (.txt)',
    noHistory: 'စကားပြောမှတ်တမ်း မရှိသေးပါ။'
  },
  ne: {
    tagline: 'प्रत्यक्ष दुईतर्फी उपशीर्षक अनुवादक',
    subdesc: '२० भाषामा मोबाइल ब्राउजर मार्फत प्रत्यक्ष उपशीर्षक अनुवाद',
    selectLang: 'आफ्नो भाषा छान्नुहोस् (Select Language)',
    searchPlaceholder: 'भाषा वा देश खोज्नुहोस्...',
    createTitle: 'नयाँ बैठक कोठा बनाउनुहोस्',
    createDesc: 'कोठा कोड र QR कोड बनाउन बटन थिच्नुहोस्।',
    createBtn: 'कोठा बनाउनुहोस् (Create Room)',
    roomCodeLabel: 'कोठा कोड:',
    qrDesc: 'तलको QR कोड स्क्यान गर्नुहोस् वा लिङ्क पठाउनुहोस्।',
    copyLinkBtn: 'निमन्त्रणा लिङ्क प्रतिलिपि गर्नुहोस्',
    copiedNotice: 'लिङ्क प्रतिलिपि गरियो!',
    enterRoomBtn: 'कोठामा प्रवेश गर्नुहोस्',
    joinTitle: 'कोठा कोड प्रयोग गरी सामेल हुनुहोस्',
    joinInputPlaceholder: 'उदा: TC-8492',
    joinBtn: 'सामेल हुनुहोस्',
    settingsBtn: 'अनुवाद इन्जिन र Gemini AI सेटिङहरू',
    waitingSubtitle: 'साथीको उपशीर्षक पर्खिँदै...',
    speaking: 'सुन्दैछ... (Speaking)',
    preview: 'मेरो उपशीर्षक पूर्वावलोकन',
    inputPlaceholder: 'सन्देश टाइप गर्नुहोस् वा बोल्न माइक थिच्नुहोस्...',
    send: 'पठाउनुहोस्',
    leave: 'छोड्नुहोस्',
    connected: 'जोडियो (Connected)',
    waitingPartner: 'साथी सामेल हुन पर्खिँदै...',
    transcript: 'कुराकानी इतिहास',
    saveTxt: 'सुरक्षित गर्नुहोस् (.txt)',
    noHistory: 'कुनै इतिहास फेला परेन।'
  },
  lo: {
    tagline: 'ລະບົບແປຄຳບັນຍາຍສົນທະນາແບບສົດໆ 2 ທິດທາງ',
    subdesc: 'ລະບົບແປຄຳບັນຍາຍ 20 ພາສາຜ່ານມືຖື',
    selectLang: 'ເລືອກພາສາຂອງທ່ານ (Select Language)',
    searchPlaceholder: 'ຄົ້ນຫາພາສາ...',
    createTitle: 'ສ້າງຫ້ອງປະຊຸມໃໝ່',
    createDesc: 'ກົດປຸ່ມເພື່ອສ້າງລະຫັດຫ້ອງ ແລະ QR Code.',
    createBtn: 'ສ້າງຫ້ອງ (Create Room)',
    roomCodeLabel: 'ລະຫັດຫ້ອງ:',
    qrDesc: 'ສະແກນ QR Code ຫຼື ສົ່ງລິ້ງໃຫ້ຄູ່ສົນທະນາຂອງທ່ານ.',
    copyLinkBtn: 'ຄັດລອກລິ້ງເຊີນ',
    copiedNotice: 'ຄັດລອກລິ້ງແລ້ວ!',
    enterRoomBtn: 'ເຂົ້າສູ່ຫ້ອງ (Enter Room)',
    joinTitle: 'ເຂົ້າຮ່ວມດ້ວຍລະຫັດຫ້ອງ',
    joinInputPlaceholder: 'ຕົວຢ່າງ: TC-8492',
    joinBtn: 'ເຂົ້າຮ່ວມ',
    settingsBtn: 'ການຕັ້ງຄ່າແປພາສາ & Gemini AI',
    waitingSubtitle: 'ກຳລັງລໍຖ້າຄຳບັນຍາຍຈາກຄູ່ສົນທະນາ...',
    speaking: 'ກຳລັງຟັງ...',
    preview: 'ຕົວຢ່າງຄຳບັນຍາຍຂອງຂ້ອຍ',
    inputPlaceholder: 'ພິມຂໍ້ຄວາມ ຫຼື ກົດໄມໂຄຣໂຟນ...',
    send: 'ສົ່ງ',
    leave: 'ອອກ',
    connected: 'ເຊື່ອມຕໍ່ແລ້ວ (Connected)',
    waitingPartner: 'ກຳລັງລໍຖ້າຄູ່ສົນທະນາ...',
    transcript: 'ປະຫວັດການສົນທະນາ',
    saveTxt: 'ບັນທຶກ (.txt)',
    noHistory: 'ຍັງບໍ່ມີປະຫວັດການສົນທະນາ.'
  },
  si: {
    tagline: 'සජීවී ද්වි-මාර්ග උපසිරැසි පරිවර්තකය',
    subdesc: 'භාෂා 20 කින් සජීවී උපසිරැසි පරිවර්තනය',
    selectLang: 'ඔබේ භාෂාව තෝරන්න (Select Language)',
    searchPlaceholder: 'භාෂාව සොයන්න...',
    createTitle: 'නව රැස්වීම් කාමරයක් සාදන්න',
    createDesc: 'කාමර කේතය සහ QR කේතය සෑදීමට බොත්තම ඔබන්න.',
    createBtn: 'කාමරය සාදන්න (Create Room)',
    roomCodeLabel: 'කාමර කේතය:',
    qrDesc: 'පහත QR කේතය ස්කෑන් කරන්න හෝ සබැඳිය බෙදා ගන්න.',
    copyLinkBtn: 'ආරාධනා සබැඳිය පිටපත් කරන්න',
    copiedNotice: 'සබැඳිය පිටපත් කරන ලදී!',
    enterRoomBtn: 'කාමරයට ඇතුළු වන්න',
    joinTitle: 'කාමර කේතයෙන් සම්බන්ධ වන්න',
    joinInputPlaceholder: 'උදා: TC-8492',
    joinBtn: 'සම්බන්ධ වන්න',
    settingsBtn: 'පරිවර්තන සහ Gemini AI සැකසුම්',
    waitingSubtitle: 'සහකරුගේ උපසිරැසි ලැබෙන තෙක් රැඳී සිටින්න...',
    speaking: 'සවන් දෙමින්... (Speaking)',
    preview: 'මගේ උපසිරැසි පෙරදසුන',
    inputPlaceholder: 'පණිවිඩයක් ලියන්න හෝ මයික්‍රෆෝනය ඔබන්න...',
    send: 'යවන්න',
    leave: 'පිටවන්න',
    connected: 'සම්බන්ධ විය (Connected)',
    waitingPartner: 'සහකරු සම්බන්ධ වන තෙක් රැඳී සිටින්න...',
    transcript: 'සංවාද සටහන',
    saveTxt: 'සුරකින්න (.txt)',
    noHistory: 'තවම සංවාද සටහන් නැත.'
  },
  bn: {
    tagline: 'রিয়েল-টাইম দ্বিমুখী সাবটাইটেল অনুবাদক',
    subdesc: '২০টি ভাষায় মোবাইল ব্রাউজারে লাইভ সাবটাইটেল অনুবাদ',
    selectLang: 'আপনার ভাষা নির্বাচন করুন (Select Language)',
    searchPlaceholder: 'ভাষা বা দেশ খুঁজুন...',
    createTitle: 'নতুন মিটিং রুম তৈরি করুন',
    createDesc: 'রুম কোড এবং কিউআর কোড তৈরি করতে বোতামে ক্লিক করুন।',
    createBtn: 'রুম তৈরি করুন (Create Room)',
    roomCodeLabel: 'রুম কোড:',
    qrDesc: 'নিচের QR কোড স্ক্যান করুন বা লিঙ্কটি শেয়ার করুন।',
    copyLinkBtn: 'আমন্ত্রণ লিঙ্ক কপি করুন',
    copiedNotice: 'লিঙ্ক ক্লিপবোর্ডে কপি করা হয়েছে!',
    enterRoomBtn: 'রুমে প্রবেশ করুন',
    joinTitle: 'রুম কোড দিয়ে যুক্ত হন',
    joinInputPlaceholder: 'যেমন: TC-8492',
    joinBtn: 'যুক্ত হন',
    settingsBtn: 'অনুবাদ ইঞ্জিন এবং Gemini AI সেটিংস',
    waitingSubtitle: 'সঙ্গীর সাবটাইটেলের জন্য অপেক্ষা করা হচ্ছে...',
    speaking: 'কথা শোনা হচ্ছে...',
    preview: 'আমার সাবটাইটেল প্রিভিউ',
    inputPlaceholder: 'মেসেজ লিখুন বা কথা বলতে মাইক চাপুন...',
    send: 'পাঠান',
    leave: 'বের হন',
    connected: 'সংযুক্ত (Connected)',
    waitingPartner: 'সঙ্গীর যোগদানের অপেক্ষা করা হচ্ছে...',
    transcript: 'কথোপকথন ইতিহাস',
    saveTxt: 'সংরক্ষণ (.txt)',
    noHistory: 'এখনও কোনো ইতিহাস নেই।'
  },
  ur: {
    tagline: 'براہ راست دو طرفہ سب ٹائٹل مترجم',
    subdesc: '20 زبانوں میں لائیو سب ٹائٹل ترجمہ کا نظام',
    selectLang: 'اپنی زبان منتخب کریں (Select Language)',
    searchPlaceholder: 'زبان یا ملک تلاش کریں...',
    createTitle: 'نیا میٹنگ روم بنائیں',
    createDesc: 'روم کوڈ اور کیو آر کوڈ بنانے کے لیے بٹن دبائیں۔',
    createBtn: 'روم بنائیں (Create Room)',
    roomCodeLabel: 'روم کوڈ:',
    qrDesc: 'نیچے دیا گیا QR کوڈ اسکین کریں یا لنک شیئر کریں۔',
    copyLinkBtn: 'دعوت نامہ کا لنک کاپی کریں',
    copiedNotice: 'لنک کاپی ہو گیا!',
    enterRoomBtn: 'روم میں داخل ہوں',
    joinTitle: 'روم کوڈ کے ساتھ شامل ہوں',
    joinInputPlaceholder: 'مثال: TC-8492',
    joinBtn: 'شامل ہوں',
    settingsBtn: 'ترجمہ انجن اور Gemini AI سیٹنگز',
    waitingSubtitle: 'ساتھی کے سب ٹائٹلز کا انتظار ہے...',
    speaking: 'آواز سنی جا رہی ہے...',
    preview: 'میرے سب ٹائٹل کا پیش منظر',
    inputPlaceholder: 'پیغام ٹائپ کریں یا بولنے کے لیے مائیک دبائیں...',
    send: 'بھیجیں',
    leave: 'چھوڑیں',
    connected: 'منسلک ہو گیا (Connected)',
    waitingPartner: 'ساتھی کے شامل ہونے کا انتظار ہے...',
    transcript: 'گفتگو کا ریکارڈ',
    saveTxt: 'محفوظ کریں (.txt)',
    noHistory: 'ابھی تک کوئی ریکارڈ موجود نہیں ہے۔'
  },
  kk: {
    tagline: 'Нақты уақыттағы екіжақты субтитр аудармашысы',
    subdesc: '20 тілде тікелей субтитр аудару жүйесі',
    selectLang: 'Тіліңізді таңдаңыз (Select Language)',
    searchPlaceholder: 'Тілді немесе елді іздеу...',
    createTitle: 'Жаңа бөлме жасау',
    createDesc: 'Бөлме кодын және QR кодты жасау үшін батырманы басыңыз.',
    createBtn: 'Бөлме жасау (Create Room)',
    roomCodeLabel: 'Бөлме коды:',
    qrDesc: 'Төмендегі QR кодты сканерлеңіз немесе сілтемені жіберіңіз.',
    copyLinkBtn: 'Сілтемені көшіру',
    copiedNotice: 'Сілтеме көшірілді!',
    enterRoomBtn: 'Бөлмеге кіру (Enter Room)',
    joinTitle: 'Бөлме кодымен кіру',
    joinInputPlaceholder: 'Мысалы: TC-8492',
    joinBtn: 'Кіру',
    settingsBtn: 'Аударма жүйесі және Gemini AI баптаулары',
    waitingSubtitle: 'Сұхбаттасушы субтитрлерін күтуде...',
    speaking: 'Дауысты тану жүруде...',
    preview: 'Менің субтитрлерім',
    inputPlaceholder: 'Хабарлама жазыңыз немесе микрофонды басыңыз...',
    send: 'Жіберу',
    leave: 'Шығу',
    connected: 'Қосылды (Connected)',
    waitingPartner: 'Сұхбаттасушыны күтуде...',
    transcript: 'Әңгімелесу жазбасы',
    saveTxt: 'Сақтау (.txt)',
    noHistory: 'Әзірге сұхбат тарихы жоқ.'
  },
  ky: {
    tagline: 'Чыныгы убакыттагы эки тараптуу субтитр котормочу',
    subdesc: '20 тилде түз эфирдеги субтитр которуу тутуму',
    selectLang: 'Тилиңизди тандаңыз (Select Language)',
    searchPlaceholder: 'Тилди же өлкөнү издөө...',
    createTitle: 'Жаңы бөлмө түзүү',
    createDesc: 'Бөлмө кодун жана QR кодун алуу үчүн баскычты басыңыз.',
    createBtn: 'Бөлмө түзүү (Create Room)',
    roomCodeLabel: 'Бөлмө коду:',
    qrDesc: 'Төмөнкү QR кодду сканерлеңиз же шилтемени жөнөтүңүз.',
    copyLinkBtn: 'Шилтемени көчүрүү',
    copiedNotice: 'Шилтеме көчүрүлдү!',
    enterRoomBtn: 'Бөлмөгө кирүү (Enter Room)',
    joinTitle: 'Бөлмө коду менен кирүү',
    joinInputPlaceholder: 'Мисалы: TC-8492',
    joinBtn: 'Кирүү',
    settingsBtn: 'Котормо тутуму жана Gemini AI жөндөөлөрү',
    waitingSubtitle: 'Маектештин субтитрлерин күтүүдө...',
    speaking: 'Үн угулууда...',
    preview: 'Менин субтитрлерим',
    inputPlaceholder: 'Билдирүү жазыңыз же сүйлөө үчүн микрофонду басыңыз...',
    send: 'Жөнөтүү',
    leave: 'Чыгуу',
    connected: 'Туташты (Connected)',
    waitingPartner: 'Маектештин кошулушун күтүүдө...',
    transcript: 'Маектешүү тарыхы',
    saveTxt: 'Сактоо (.txt)',
    noHistory: 'Маектешүү тарыхы азырынча жок.'
  }
};

export function getUIText(langCode) {
  return UI_TEXTS[langCode] || UI_TEXTS.ko;
}
